# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NearBy' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NearBy

  pod 'SwiftyJSON'
  pod 'Alamofire'
  pod 'PKHUD'
  pod 'IQKeyboardManagerSwift'
  pod 'SDWebImage'

  target 'NearByTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NearByUITests' do
    # Pods for testing
  end

end
